_prefs: 
  baselayer: ''
  mapid: skorasaurus.67b7e400
  saveCenter: true
_properties: {}
attribution: Map data © OpenStreetMap contributors
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -81.4938
  - 40.4947
  - 11
description: 'welcome to a new world order. '
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 17
minzoom: 0
name: nW0
source: "mapbox:///mapbox.mapbox-streets-v4"
styles: 
  - style.mss
template: ''
